;; rbac-docs.lisp

(in-package :rbac)

(defmacro defsection-wrapper (name (&rest options) doc-string &body body)
  `(defsection ,name ,options ,(eval doc-string) ,@body))

(defsection-wrapper @rbac-manual
  (:title "RBAC System Reference Manual")
  (u:slurp (u:join-paths
             (asdf:system-relative-pathname :rbac #P"")
             "intro-src.md"))
  (@rbac-examples section)
  (@rbac-pg-class section)
  (@rbac-functions section)
  (@rbac-variables section)
  (@rbac-macros section))

(defsection @rbac-pg-class
  (:title "RBAC-PG Class")
  "RBAC-PG Class and Accessors."
  (rbac-pg class)
  (db-host (accessor rbac-pg))
  (db-name (accessor rbac-pg))
  (db-password (accessor rbac-pg))
  (db-port (accessor rbac-pg))
  (db-user (accessor rbac-pg))
  (email-length-max (accessor rbac))
  (email-regex (accessor rbac))
  (password-length-max (accessor rbac))
  (password-length-min (accessor rbac))
  (password-regexes (accessor rbac))
  (permission-length-max (accessor rbac))
  (permission-regex (accessor rbac))
  (resource-length-max (accessor rbac))
  (resource-regex (accessor rbac))
  (role-length-max (accessor rbac))
  (role-regex (accessor rbac))
  (user-name-length-max (accessor rbac))
  (user-name-regex (accessor rbac)))

(defsection @rbac-functions
  (:title "Functions")
  "Accessors and methods for manipulating RBAC objects."
  (add-permission function)
  (add-resource function)
  (add-resource-role function)
  (add-role function)
  (add-role-permission function)
  (add-role-user function)
  (add-user function)
  (add-user-role function)
  (exclusive-role-for function)
  (get-id function)
  (get-value function)
  (id-exists-p function)
  (initialize-database function)
  (list-permission-names function)
  (list-permissions function)
  (list-resource-names function)
  (list-resource-role-names function)
  (list-resource-roles function)
  (list-resource-user-names function)
  (list-resource-users function)
  (list-resources function)
  (list-role-names function)
  (list-role-permission-names function)
  (list-role-permissions function)
  (list-role-resource-names function)
  (list-role-resources function)
  (list-role-user-names function)
  (list-role-users function)
  (list-roles function)
  (list-user-names function)
  (list-user-resource-names function)
  (list-user-resource-permission-names function)
  (list-user-resources function)
  (list-user-role-names function)
  (list-user-roles function)
  (list-users function)
  (login function)
  (password-hash function)
  (password-hash function)
  (permission-count function)
  (rbac-query function)
  (rbac-query-single function)
  (remove-permission function)
  (remove-resource function)
  (remove-resource-role function)
  (remove-role function)
  (remove-role-permission function)
  (remove-role-user function)
  (remove-user function)
  (remove-user-role function)
  (resource-count function)
  (resource-role-count function)
  (resource-user-count function)
  (role-count function)
  (role-permission-count function)
  (role-resource-count function)
  (role-user-count function)
  (user-allowed function)
  (user-count function)
  (user-has-role function)
  (user-resource-count function)
  (user-role-count function)
  (valid-description-p function)
  (valid-email-p function)
  (valid-password-p function)
  (valid-permission-p function)
  (valid-resource-p function)
  (valid-role-p function)
  (valid-user-name-p function))

(defsection @rbac-macros
  (:title "Macros")
  "Exported macros."
  (with-rbac macro))

(defsection @rbac-variables
  (:title "Special Variables")
  "Exported special variables."
  (*admin* variable)
  (*guest* variable)
  (*default-page-size* variable)
  (*default-permissions* variable)
  (*default-resource-roles* variable)
  (*default-user-roles* variable))

(defsection-wrapper @rbac-examples
  (:title "Examples")
  (u:slurp (u:join-paths
             (asdf:system-relative-pathname :rbac #P"")
             "examples-src.md")))

(defun generate-readme ()
  (let ((file-name (u:join-paths
                     (asdf:system-relative-pathname :rbac #P"")
                     "README.md")))
    (with-open-file (stream file-name :direction :output :if-exists :supersede)
      (document @rbac-manual :format :markdown :stream stream))))
