(in-package :rbac)

(defmacro defsection-wrapper (name (&rest options) doc-string &body body)
  `(defsection ,name ,options ,(eval doc-string) ,@body))

(defsection-wrapper @rbac-manual
  (:title "RBAC System Reference Manual")
  (u:slurp (u:join-paths
             (asdf:system-relative-pathname :rbac #P"")
             "intro-src.md"))
  (@rbac-examples section)
  (@rbac-classes section)
  (@rbac-functions section)
  (@rbac-macros section))

(defsection @rbac-classes
  (:title "Classes")
  "Core classes for the RBAC system."
  (rbac class)
  (rbac-pg class))

(defsection @rbac-functions
  (:title "Functions")
  "Accessors and methods for manipulating RBAC objects."
  (add-permission function)
  (add-resource function)
  (add-resource-role function)
  (add-role function)
  (add-role-permission function)
  (add-role-user function)
  (add-user function)
  (add-user-role function)
  (get-id function)
  (get-value function)
  (id-exists-p function)
  (initialize-database function)
  (list-permission-names function)
  (list-permissions function)
  (list-user-names function)
  (list-users function)
  (login function)
  (password-hash function)
  (permission-count function)
  (remove-permission function)
  (remove-resource function)
  (remove-resource-role function)
  (remove-role function)
  (remove-role-permission function)
  (remove-role-user function)
  (remove-user function)
  (remove-user-role function)
  (resource-length-max (accessor rbac))
  (resource-regex (accessor rbac))
  (user-allowed function)
  (user-count function)
  (user-has-role function)
  (user-name-length-max (accessor rbac))
  (user-name-regex (accessor rbac))
  (valid-description-p function)
  (valid-email-p function)
  (valid-password-p function)
  (valid-permission-p function)
  (valid-resource-p function)
  (valid-role-p function)
  (valid-user-name-p function)
  (list-resources function)
  (list-resource-names function)
  (resource-count function)
  (list-user-roles function)
  (list-user-role-names function)
  (user-role-count function)
  (list-role-permissions function)
  (list-role-permission-names function)
  (role-permission-count function)
  (list-role-users function)
  (list-role-user-names function)
  (role-user-count function)
  (list-role-resources function)
  (list-role-resource-names function)
  (role-resource-count function)
  (list-resource-roles function)
  (list-resource-role-names function)
  (resource-role-count function)
  (list-user-resources function)
  (list-user-resource-names function)
  (user-resource-count function)
  (list-resource-users function)
  (list-resource-user-names function)
  (resource-user-count function)
  (list-user-resource-permission-names function)
  (password-hash function))

(defsection @rbac-macros
  (:title "Macros")
  "Exported macros."
  (with-rbac macro))

(defsection-wrapper @rbac-examples
  (:title "Examples")
  (u:slurp (u:join-paths
             (asdf:system-relative-pathname :rbac #P"")
             "examples-src.md")))

(defun generate-readme ()
  (let ((file-name (u:join-paths
                     (asdf:system-relative-pathname :rbac #P"")
                     "README.md")))
    (with-open-file (stream file-name :direction :output :if-exists :supersede)
      (document @rbac-manual :format :markdown :stream stream))))
