;; rbac-package.lisp

(defpackage :rbac
  (:use :cl :mgl-pax)
  (:local-nicknames
    (:ds :dc-ds)
    (:u :dc-eclectic)
    (:re :ppcre)
    (:l :p-log)
    (:db :postmodern))
  (:export
    *admin*
    *default-page-size*
    *default-permissions*
    *default-resource-roles*
    *default-user-roles*
    *guest*
    add-permission
    add-resource
    add-resource-role
    add-role
    add-role-permission
    add-role-user
    add-user
    add-user-role
    db-name
    email-length-max
    email-regex
    exclusive-role-for
    get-id
    get-value
    db-host
    id-exists-p
    initialize-database
    list-permission-names
    list-permissions
    list-resource-names
    list-resource-role-names
    list-resource-roles
    list-resource-user-names
    list-resource-users
    list-resources
    list-role-names
    list-role-permission-names
    list-role-permissions
    list-role-resource-names
    list-role-resources
    list-role-user-names
    list-role-users
    list-roles
    list-user-names
    list-user-resource-names
    list-user-resource-names-of-type
    list-user-resource-permission-names
    list-user-resources
    list-user-role-names
    list-user-roles
    list-users
    login
    db-password
    password-hash
    password-length-max
    password-length-min
    password-regexes
    permission-count
    permission-length-max
    permission-regex
    db-port
    rbac
    rbac-pg
    rbac-query
    rbac-query-single
    remove-permission
    remove-resource
    remove-resource-role
    remove-role
    remove-role-permission
    remove-role-user
    remove-user
    remove-user-role
    resource-count
    resource-length-max
    resource-regex
    resource-role-count
    resource-user-count
    role-count
    role-length-max
    role-permission-count
    role-regex
    role-resource-count
    role-user-count
    user-allowed
    user-count
    user-has-role
    db-user
    user-name-length-max
    user-name-regex
    user-resource-count
    user-role-count
    valid-description-p
    valid-email-p
    valid-password-p
    valid-permission-p
    valid-resource-p
    valid-role-p
    valid-user-name-p
    with-rbac
    ))
