#!/bin/bash

#
# Starts the rbac repl
#

STOP=false

# File Server Lisp Environment
export DB_HOST="127.0.0.1"
export DB_PORT="5436"
export DB_NAME="rbac"
export DB_USER="rbac"
export DB_PASSWORD="rbac-password"
export DB_CONTAINER="pg-rbac-test"
export LOG_FILE=$(readlink -f "$PWD/tests/rbac.log")
export SWANK_PORT="4008"

# Needed to avoid prompting in psql calls
export PGPASSWORD="$DB_PASSWORD"

function usage {
    echo "Usage: $SCRIPT_NAME [options]"
    echo
    echo "Starts the RBAC REPL. Once the service is running, you can interact with"
    echo "the REPL in the shell, or you can connect to the REPL via Slime, at the"
    echo "given Swank port. When stop the REPL, this script uses docker compose to"
    echo "terminate the PostgreSQL service."
    echo
    echo "Options:"
    echo "  --db-port      The host port for the PosgreSQL database. Defaults to 5435."
    echo "  --swank-port   The host port for the Swank service. Defaults to 4006."
    echo "  --stop         Stop the PostgreSQL service. Normally, this script stops"
    echo "                 the service automatically. This option allows you to stop"
    echo "                 the service explicitly if the script fails before it can"
    echo "                 stop the service itself."
}

while [ $# -gt 0 ]; do
    case "$1" in
        --stop)
            STOP=true
            ;;
        --db-port)
            shift
            DB_PORT="$1"
            ;;
        --swank-port)
            shift
            SWANK_PORT="$1"
            ;;
        --help)
            usage
            exit 0
            ;;
        help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option $1"
            exit 1
            ;;
    esac
    shift
done

if [[ "$STOP" = false ]]; then
	echo
	echo "Starting PosgreSQL"
	docker-compose -f tests/docker-compose-pg.yaml up -d &>/dev/null

	echo
	echo "Waiting for PostgreSQL"
	until docker-compose -f tests/docker-compose-pg.yaml exec -it $DB_CONTAINER \
	  pg_isready -U postgres &>/dev/null; do
	  echo "  Waiting..."
	  sleep 1
	done
	echo "PostgreSQL is up on port ${DB_PORT}"
	sleep 2

	echo
	echo "Initializing database"
	psql -h $DB_HOST -p $DB_PORT -f -d $DB_NAME -U $DB_USER \
       -f tests/db-init/init.sql >&/dev/null

	echo
	echo "Starting RBAC REPL"
	ros run -- --load "tests/rbac-repl.lisp"
fi

echo "Stopping PostgreSQL"
if [[ "$STOP" = false ]]; then
    # Stop normally (quietly)
    docker-compose -f tests/docker-compose-pg.yaml down &>/dev/null
else
    # Exclicit --stop, so stop verbosely
    docker-compose -f tests/docker-compose-pg.yaml down
fi
