#!/bin/bash

# Start PostgreSQL and wait until it's available
docker-compose -f tests/docker-compose-pg.yaml up -d &>/dev/null
until docker-compose -f tests/docker-compose-pg.yaml exec -it pgtest \
  pg_isready -U postgres &>/dev/null; do
  echo "Waiting for postgres..."
  sleep 1
done
echo "PostgreSQL is up!"
sleep 1

# Run the tests
ros run -- --load "tests/rbac-test-1.lisp" --quit

# Stop PostgreSQL
docker-compose -f tests/docker-compose-pg.yaml down &>/dev/null
