#!/bin/bash

docker compose --progress quiet up --abort-on-container-exit
RESULT=$?
docker compose --progress quiet down
echo
if [[ $RESULT -eq 0 ]]; then
    echo ">>>> PASS <<<<"
else
    echo ">>>> FAIL <<<<"
fi
echo
exit $RESULT
