#!/bin/bash

TEST_FILE=$1

# File Server Lisp Environment
export DB_HOST="127.0.0.1"
export DB_PORT="5436"
export DB_NAME="rbac"
export DB_USER="rbac"
export DB_PASSWORD="rbac-password"
export ADMIN_PASSWORD="admin-password-1"
export DB_CONTAINER="pg-rbac-test"
export LOG_FILE=$(readlink -f "$PWD/tests/tests.log")
export RBAC_REPL="false"
export RUN_TESTS="false"
export SKIP_DB="true"

if [[ -z "$TEST_FILE" ]]; then
    echo "Usage: $(basename $0) {test-file}"
    exit 1
fi

ros run -- --disable-debugger \
  --eval '(asdf:load-system :rbac :force t)' \
  --load "$TEST_FILE" \
  --eval "(rbac::generate-readme)" --quit
if [[ $? -eq 0 ]]; then
    echo "Generated README.md"
else
    echo "Failed to generate README.md"
fi
